In [5]:
print("Shape:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nCredit History Values:")
print(df["credit_history"].unique())

print("\nTarget Distribution:")
print(df["credit_risk"].value_counts())

Shape: (200, 5)

Column Names:
['age', 'income', 'credit_history', 'loan_amount', 'credit_risk']

Data Types:
age               int64
income            int64
credit_history      str
loan_amount       int64
credit_risk       int64
dtype: object

Missing Values:
age               0
income            0
credit_history    0
loan_amount       0
credit_risk       0
dtype: int64

Credit History Values:
<StringArray>
['Fair', 'Good', 'Poor']
Length: 3, dtype: str

Target Distribution:
credit_risk
0    140
1     60
Name: count, dtype: int64

In [6]:
df = pd.get_dummies(df, columns=["credit_history"], dtype=int)

display(df.head())

,age,income,loan_amount,credit_risk,credit_history_Fair,credit_history_Good,credit_history_Poor
0,53,87,22,0,1,0,0
1,39,51,9,0,0,1,0
2,32,108,29,0,0,1,0
3,45,76,6,0,0,1,0
4,43,71,14,0,0,1,0

In [7]:
X = df.drop("credit_risk", axis=1)
y = df["credit_risk"]

print("Features:")
display(X.head())

print("Target:")
display(y.head())

Features:

,age,income,loan_amount,credit_history_Fair,credit_history_Good,credit_history_Poor
0,53,87,22,1,0,0
1,39,51,9,0,1,0
2,32,108,29,0,1,0
3,45,76,6,0,1,0
4,43,71,14,0,1,0

Target:

0    0
1    0
2    0
3    0
4    0
Name: credit_risk, dtype: int64

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (160, 6)
Testing data: (40, 6)

In [9]:
model = DecisionTreeClassifier(random_state=42)

model.fit(X_train, y_train)

print("Decision Tree model trained successfully.")

Decision Tree model trained successfully.

In [10]:
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.725